name: Meaningful Magic
favicon: null
layout_spectrum: 0.9974
typography_spectrum: 0.99287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080605'
    - '#e07b23'
    - '#865220'
    - '#ffffff'
    - '#ffbc32'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
